[build]
  base = "frontend/"
  publish = "dist/support-ticketing-frontend"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-backend-url.herokuapp.com/api"